---
steps:
  # setup gcloud testing
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cp e2e_test/gcloud/openapi.yaml functions/restingest/openapi_server/openapi.yaml
        cp e2e_test/gcloud/config.py functions/restingest/config.py
        gcloud functions deploy ${PROJECT_ID}-ingest-func \
        --entry-point=http_receive_store_blob_trigger_func \
        --update-env-vars=[STORAGE_BUCKET=$_STORAGE_BUCKET] \
        --runtime=python37 \
        --trigger-http \
        --project=${PROJECT_ID} \
        --region=europe-west1
    dir: '../functions/restingest'

substitutions:
  _STORAGE_BUCKET: "Please set substitution _STORAGE_BUCKET in cloudbuild file"
