---
steps:
  # Clone restingest repository
  - name: 'gcr.io/cloud-builders/git'
    args:
      - 'clone'
      - '--branch=develop'
      - 'https://github.com/vwt-digital/restingest.git'

  # Copy config to cloud functions
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    id: 'copy config'
    args:
      - '-c'
      - |
        cp -r restingest/functions/restingest prepareconfig
        cp restingest/e2e_test/gcloud/openapi.yaml prepareconfig/openapi_server/openapi/openapi.yaml
        cp restingest/e2e_test/gcloud/openapi.yaml getconfig/openapi_server/openapi/openapi.yaml
        cp restingest/e2e_test/gcloud/config.py prepareconfig/config.py
        cp restingest/e2e_test/gcloud/get.config.py getconfig/config.py

  # Deploy restingest function to set data
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    id: 'deploy & set test'
    args:
      - '-c'
      - |
        gcloud functions deploy \
        ${PROJECT_ID}-ingest-func \
        --entry-point=http_receive_store_blob_trigger_func \
        --runtime=python37 \
        --trigger-http \
        --timeout=480 \
        --memory=2048MB \
        --project=${PROJECT_ID} \
        --region=europe-west1 \
        --set-env-vars=PROJECT_ID=${PROJECT_ID},STORAGE_BUCKET=$_STORAGE_BUCKET
    dir: 'prepareconfig'

  # Deploy restingest function to get data
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    id: 'deploy & get test'
    args:
      - '-c'
      - |
        gcloud functions deploy \
        ${PROJECT_ID}-ingest-func \
        --entry-point=http_request_store_blob_trigger_func \
        --runtime=python37 \
        --trigger-http \
        --timeout=480 \
        --memory=2048MB \
        --project=${PROJECT_ID} \
        --region=europe-west1 \
        --set-env-vars=PROJECT_ID=${PROJECT_ID}
    dir: 'getconfig'
    env:
      - 'STORAGE_BUCKET=$_STORAGE_BUCKET'

substitutions:
  _STORAGE_BUCKET: "Please_set_substitution_'_STORAGE_BUCKET'_in_cloudbuild_file"
