---
steps:
  # Clone restingest repository
  - name: 'gcr.io/cloud-builders/git'
    args:
      - 'clone'
      - '--branch=develop'
      - 'https://github.com/vwt-digital/restingest.git'

  # Copy config to cloud functions
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    id: 'copy config'
    args:
      - '-c'
      - |
        cp -r restingest/functions/restingest postconfig
        cp -r restingest/functions/restingest getconfig
        cp restingest/e2e_test/config/post.openapi.yaml postconfig/openapi_server/openapi/openapi.yaml
        cp restingest/e2e_test/config/get.openapi.yaml getconfig/openapi_server/openapi/openapi.yaml
        cp restingest/e2e_test/config/post.config.py postconfig/config.py
        cp restingest/e2e_test/config/get.config.py getconfig/config.py

  # Deploy restingest function for posting/receiving data
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    id: 'deploy post/receive test'
    args:
      - '-c'
      - |
        gcloud functions deploy \
        ${PROJECT_ID}-receive-ingest-func \
        --allow-unauthenticated \
        --entry-point=http_receive_store_blob_trigger_func \
        --runtime=python37 \
        --trigger-http \
        --timeout=480 \
        --memory=2048MB \
        --project=${PROJECT_ID} \
        --region=europe-west1 \
        --set-env-vars=PROJECT_ID=${PROJECT_ID},STORAGE_BUCKET=$_STORAGE_BUCKET
    dir: 'postconfig'

  # Deploy restingest function to getting/requesting data
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    id: 'deploy get/request test'
    args:
      - '-c'
      - |
        gcloud functions deploy \
        ${PROJECT_ID}-request-ingest-func \
        --entry-point=http_request_store_blob_trigger_func \
        --runtime=python37 \
        --trigger-http \
        --timeout=480 \
        --memory=2048MB \
        --project=${PROJECT_ID} \
        --region=europe-west1 \
        --set-env-vars=PROJECT_ID=${PROJECT_ID},STORAGE_BUCKET=$_STORAGE_BUCKET
        echo '{ "bindings": [ { "members": [ "serviceAccount:${_SERVICE}@cloudbuild.gserviceaccount.com" ], "role": "roles/cloudfunctions.invoker" } ] }' > consume_func_permissions.json
        gcloud beta functions set-iam-policy ${PROJECT_ID}-ingest-func --region=europe-west1 --project=${PROJECT_ID} consume_func_permissions.json
    dir: 'getconfig'

  # Run E2E tests
  # Continue on failure to guarantee functions get deleted
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    id: 'run E2E tests'
    args:
      - '-c'
      - |
        export domain="${PROJECT_ID}"
        python -m pip install -r restingest/e2e_test/requirements-test.txt
        python -m unittest discover --verbose -p test.py restingest/e2e_test/ || touch /workspace/persistent_failure_file

  # Delete restingest functions after tests have run
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    id: 'Delete restingest functions'
    args:
      - '-c'
      - |
        gcloud functions delete ${PROJECT_ID}-receive-ingest-func --region europe-west1 --quiet
        gcloud functions delete ${PROJECT_ID}-request-ingest-func --region europe-west1 --quiet

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    id: 'Fail on test failure after function deletion'
    args:
      - '-c'
      - |
        ! test -f /workspace/persistent_failure_file

substitutions:
  _STORAGE_BUCKET: "Please_set_substitution_'_STORAGE_BUCKET'_in_cloudbuild_file"
  _SERVICE: "Please_set_service_'_SERVICE'_in_cloudbuild_file"
