---
steps:
  # Clone restingest repository
  - name: 'gcr.io/cloud-builders/git'
    args:
      - 'clone'
      - '--branch=develop'
      - 'https://github.com/vwt-digital/restingest.git'

  # Copy config to cloud functions
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    id: 'copy config'
    args:
      - '-c'
      - |
        cp -r restingest/functions/restingest postconfig
        cp -r restingest/functions/restingest getconfig
        cp restingest/e2e_test/openapi.yaml postconfig/openapi_server/openapi/openapi.yaml
        cp restingest/e2e_test/openapi.yaml getconfig/openapi_server/openapi/openapi.yaml
        cp restingest/e2e_test/config.py postconfig/config.py
        cp restingest/e2e_test/get.config.py getconfig/config.py

  # Deploy restingest function to set data
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    id: 'deploy & set test'
    args:
      - '-c'
      - |
        gcloud functions deploy \
        ${PROJECT_ID}-receive-ingest-func \
        --entry-point=http_receive_store_blob_trigger_func \
        --runtime=python37 \
        --trigger-http \
        --timeout=480 \
        --memory=2048MB \
        --project=${PROJECT_ID} \
        --region=europe-west1 \
        --set-env-vars=PROJECT_ID=${PROJECT_ID},STORAGE_BUCKET=$_STORAGE_BUCKET
    dir: 'postconfig'

  # Deploy restingest function to get data
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    id: 'deploy & get test'
    args:
      - '-c'
      - |
        gcloud functions deploy \
        ${PROJECT_ID}-request-ingest-func \
        --entry-point=http_request_store_blob_trigger_func \
        --runtime=python37 \
        --trigger-http \
        --timeout=480 \
        --memory=2048MB \
        --project=${PROJECT_ID} \
        --region=europe-west1 \
        --set-env-vars=PROJECT_ID=${PROJECT_ID},STORAGE_BUCKET=$_STORAGE_BUCKET
    dir: 'getconfig'

substitutions:
  _STORAGE_BUCKET: "Please_set_substitution_'_STORAGE_BUCKET'_in_cloudbuild_file"
