---
openapi: 3.0.1
info:
  title: restingest-test
  description: restingest generic endpoints
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  version: 1.0.0
servers:
  - url: /
paths:
  /store-json:
    post:
      summary: Store some json
      description: Store the posted json data
      operationId: generic_post
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                ID:
                  type: integer
                  format: int64
                  minimum: 1
              required:
                - ID
        required: true
      responses:
        201:
          description: Successful response.
      x-codegen-request-body-name: body
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /store-xml:
    post:
      summary: Store some xml
      description: Store the posted xml data
      operationId: generic_post2
      requestBody:
        description: A new XML document to be stored.
        content:
          application/xml: {}
        required: true
      responses:
        201:
          description: Successful response.
      x-codegen-request-body-name: body
      x-openapi-router-controller: openapi_server.controllers.default_controller
